version: "3.11"

services:

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: hillel_fastapi_example:0.0.1-dev
    container_name: hillel_fastapi_example
    command: bash docker/runserver.sh
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - '8000:8000'
    volumes:
      - .:/home/appuser/app

  database:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5433:5432"

  redis_db:
    container_name: redis_db
    image: redis:7.0-alpine
    restart: on-failure
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "ping" ]

volumes:
  database-data:
  redis-data: